name: Auto Add To Pending Discussion
on:
  issue_comment:
    types: [created]
env:
  MY_GITHUB_TOKEN: ${{ secrets.ADD_TO_PROJECT_PAT }}
jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: srggrs/assign-one-project-github-action@1.2.1
        with:
          project: 'https://github.com/orgs/jtorleon-studios-team/projects/4'
          column_name: 'Pending-Discussion'
