name: Auto Assign
on:
  workflow_dispatch:
  issues:
    types: [opened]
jobs:
  run:
    uses: jtorleon-studios-team/.workflows/.github/workflows/auto-assign.yml@main
    permissions:
      contents: read
      issues: write
      pull-requests: write
    secrets:
      ADD_TO_PROJECT_PAT : ${{ secrets.ADD_TO_PROJECT_PAT }}
    with:
      token: ${{ secrets.ACCESS_WORKFLOWS }}
