name: Auto Add To Pending Discussion
on:
  issue_comment:
    types: [created]
jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - run: gh issue edit "$NUMBER" --add-label "$LABELS"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          LABELS: "Pending Discussion"
      - uses: konradpabjan/move-labeled-or-milestoned-issue@v2.0
        env:
          MY_GITHUB_TOKEN: ${{ secrets.ADD_TO_PROJECT_PAT }}
        with:
          project-url: "https://github.com/orgs/jtorleon-studios-team/projects/4"
          column-name: "Pending Discussion"
          label-name: "Pending Discussion"
          action-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
