name: Pending Discussion
run-name: ${{ github.actor }} run ${{ github.action }}

on:
  issue_comment:
    types: [created]
  workflow_call:
    secrets:
      ADD_TO_PROJECT_PAT:
        required: true
jobs:
  run:
    if: github.actor != github.event.issue.user.login && !contains(github.event.issue.labels.*.name, 'pending discussion')
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      
      - run: gh issue edit "$NUMBER" --add-label "pending discussion" --remove-label "awaiting contributions"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
      
      - uses: actions/add-to-project@5afcf98fcd03f1c2f92c3c83f58ae24323cc57fd # v2.0.0
        with:
          project-url: https://github.com/orgs/jtorleon-studios-team/projects/4
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
        id: add-project
      
      - uses: titoportas/update-project-fields@421a54430b3cdc9eefd8f14f9ce0142ab7678751 # v0.1.0
        with:
          project-url: https://github.com/orgs/jtorleon-studios-team/projects/4
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          item-id: ${{ steps.add-project.outputs.itemId }}
          field-keys: Status
          field-values: Pending Discussion
