name: Handle Discussion

on:
  discussion:
    types: [unlocked]

jobs:
  handle-discussion:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - id: prepare-data
        name: Prepare data
        run: echo "::set-output name=text::Hello, World!"

      - name: Update discussions
        run: |
          echo "Discussion with id ${{ github.event.discussion.node_id }} unlocked in category ${{ github.event.discussion.category.name }} ${{ github.event.discussion.category.node_id }}"

          if [ "${{ github.event.discussion.category.name }}" == "Announcements" ]; then 
            response=$(curl -i -H 'Content-Type: application/json' -H "Authorization: bearer ${{ secrets.GITHUB_TOKEN }}" -X POST -d '{"query": "mutation {updateDiscussion(input: {discussionId: \"${{ github.event.discussion.node_id }}\", body: \"${{ steps.prepare-data.outputs.text }}\"}) {discussion { id } }}"}' https://api.github.com/graphql)
            if echo "$response" | grep -q '"errors"'; then
              echo "failed: $response"
              exit 1
            else 
              echo "succes: $response"
            fi
          fi
