name: Handle Discussion Unlocked
on:
  discussion:
    types: [unlocked]
jobs:
  filter-discussion:
    runs-on: ubuntu-22.04
    outputs:
      status: ${{ steps.set-output-filter.outputs.status }}
    steps:
      - id: set-output-filter
        name: Filter Discussion
        run: |
          echo "::group::Filter Discussion"
          echo "discussion ${{ github.event.discussion.node_id }} ${{ github.event.discussion.title }}"
          echo "discussion category ${{ github.event.discussion.category.node_id }} ${{ github.event.discussion.category.name }}"
          if [ "${{ github.event.discussion.category.name }}" == "Announcements" ]; then
            echo "match"
            echo "status=success" >> $GITHUB_OUTPUT
          else
            echo "ignored"
            echo "status=ignored" >> $GITHUB_OUTPUT
          fi
          echo "::endgroup::"

  handle-discussion:
    runs-on: ubuntu-22.04
    needs: filter-discussion
    if: needs.filter-discussion.outputs.status == 'success'
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - id: prepare-data
        name: Prepare data
        run: |
          str=$(echo -e "# Stay in the Loop\n## New Updates and content You'll Love! 💥\nHello!")
          encoded_str=$(echo -n "$str" | base64)
          echo "text=$encoded_str" >> $GITHUB_OUTPUT

      - name: Update Github Discussions
        run: |
          decoded_str=$(echo ${{ steps.prepare-data.outputs.text }} | base64 --decode)
          response=$(curl -i -H 'Content-Type: application/json' -H "Authorization: bearer ${{ secrets.GITHUB_TOKEN }}" -X POST -d '{"query": "mutation {updateDiscussion(input: {discussionId: \"${{ github.event.discussion.node_id }}\", body: \"$decoded_str\"}) {discussion { id } }}"}' https://api.github.com/graphql)
          if echo "$response" | grep -q '"errors"'; then
            echo "failed: $response"
            exit 1
          else 
            echo "succes: $response"
          fi
