name: Handle Discussion

on:
  discussion:
    types: [unlocked]

jobs:
  handle-discussion:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - run: |
          echo "Discussion with id ${{ github.event.discussion.id }} locked in category ${{ github.event.category.name }} ${{ github.event.category.id }}"

          if [ "${{ github.event.category.name }}" == "Announcements" ]; then
            discussion_id="${{ github.event.discussion.id }}"
            
            curl -X PATCH "https://api.github.com/discussions/${{ github.event.discussion.id }}/comments/1" \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              -d '{"body": "Updated message for the discussion"}'
            
            echo "Discussion edited"
          fi
