name: Handle Discussion

on:
  discussion:
    types: [unlocked]

jobs:
  handle-discussion:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - run: |
          echo "Discussion with id ${{ github.event.discussion.id }} unlocked in category ${{ github.event.discussion.category.name }} ${{ github.event.discussion.category.id }}"

          if [ "${{ github.event.discussion.category.name }}" == "Announcements" ]; then
            discussion_id="${{ github.event.discussion.id }}"

            query=$(jq -n \
              --arg id "$discussion_id" \
              --arg body "test" \
              '{
                "query": "mutation { updateDiscussion(input: {discussionId: \"123\", body: \"hello\" }) { discussion { id } } }"
              }')

            response=$(curl -s -X POST \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -H "Content-Type: application/json" \s
              -d "$query" \
              https://api.github.com/graphql
            )

            if echo "$response" | grep -q '"errors"'; then
              echo "failed: $response"
              exit 1
            else
              echo "succes discussion edited"
            fi

          fi
