name: Handle Discussion Created
on:
  discussion:
    types: [created]
jobs:
  filter-discussion:
    runs-on: ubuntu-22.04
    outputs:
      status: ${{ steps.set-output-filter.outputs.status }}
    steps:
      - id: set-output-filter
        name: Filter Discussion
        run: |
          echo "::group::Filter Discussion"
          echo "discussion ${{ github.event.discussion.node_id }} ${{ github.event.discussion.title }}"
          echo "discussion category ${{ github.event.discussion.category.node_id }} ${{ github.event.discussion.category.name }}"
          if [ "${{ github.event.discussion.category.name }}" == "Polls" ]; then
            echo "match"
            echo "status=success" >> $GITHUB_OUTPUT
          else
            echo "ignored"
            echo "status=ignored" >> $GITHUB_OUTPUT
          fi
          echo "::endgroup::"

  handle-discussion:
    runs-on: ubuntu-22.04
    needs: filter-discussion
    if: needs.filter-discussion.outputs.status == 'success'
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: send polls to discord
        run: |
          discussion_number="${{ github.event.discussion.number }}"
          discussion_url="https://github.com/orgs/jtorleon-studios-team/discussions/$discussion_number"
          messageToJson=$( jq -n --arg content "[A polls has been created]($discussion_url)" '{ content: $content }')
          curl -H "Content-Type: application/json" -d "${messageToJson}" ${{ secrets.POOLS_DISCORD }}
